// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app_global;

namespace db_access_sample.Migrations
{
    [DbContext(typeof(Model))]
    partial class ModelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("app_global.enumerator", b =>
                {
                    b.Property<int>("enumerator_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("enumerator_id");

                    b.Property<double>("enumerator_value")
                        .HasColumnName("enumerator_value");

                    b.HasKey("enumerator_id");

                    b.ToTable("enumerators");
                });
#pragma warning restore 612, 618
        }
    }
}
